# Final Project

* The code and explanations provided in this notebook will be helpful to develop the course final project. 

* The first section includes various functions that are used in the main function of the genetic algorithm (section 2)

* Section 3 apply the GA function using one and two generations of individuals

### 1) Functions implemented in the genetic algorithm (GA)

### Number of cities

In [1]:
n = 6

n =  6


### Matrix of distance between cities (randomly generated)

In [2]:
function d = distanceMatrixCities(n)

    d = 100*rand(n);

    ## Fill diagonal with zeros
    i = 1;
    
    while(i<=n)
        d(i,i) = 0;
        i++;
    end
    
end

In [3]:
d = distanceMatrixCities(n)

d =

    0.00000   94.44586   93.85428   12.14776    4.95983   15.67047
   75.76300    0.00000   80.46524   81.91093   93.05000   90.76333
   97.26600   98.77020    0.00000   42.85782   13.34514   80.21638
   97.69871   61.25826   87.12197    0.00000   45.28902   98.83853
   89.97178   67.60073   16.38991    7.28028    0.00000   90.94445
   59.96915   76.57118   52.24841   75.88961   92.57202    0.00000



## a) Initial population

### Total population

In [4]:
totalPop = perms([1:n]); #This built-in function allows to generate the total population of individuals

In [5]:
totalPop(1:10,:) #First 10 individuals of the total population

ans =

   6   5   4   3   2   1
   6   5   4   3   1   2
   6   5   4   2   3   1
   6   5   4   2   1   3
   6   5   4   1   3   2
   6   5   4   1   2   3
   6   5   3   4   2   1
   6   5   3   4   1   2
   6   5   3   2   4   1
   6   5   3   2   1   4



In [6]:
size(totalPop)(1) #Size of the total population

ans =  720


### Size of the initial population ("generation 0")

In [7]:
sizeGeneration0 = 20 

sizeGeneration0 =  20


### Select individuals randomly from the total population 

In [8]:
function subPop = createGeneration(totalPop,sizeGen)
    
    # This function returns a list with one element.
    # The element contains a matrix with the sequence of cities associated to each individual of the generation
    
    subPop = totalPop(randi(size(totalPop)(1),sizeGen,1),:);

end

In [9]:
# Creation of the generation 0

In [10]:
generation0 = createGeneration(totalPop = totalPop,sizeGen = sizeGeneration0)

generation0 =

   2   4   6   5   1   3
   6   2   5   1   4   3
   6   3   2   4   5   1
   1   6   3   4   5   2
   2   6   5   4   1   3
   5   1   3   2   6   4
   5   2   6   3   1   4
   4   1   2   5   3   6
   1   2   4   5   6   3
   1   2   3   5   4   6
   6   5   2   3   1   4
   5   6   4   2   3   1
   3   2   5   6   1   4
   2   1   5   4   3   6
   5   6   1   2   4   3
   4   1   6   5   2   3
   1   6   2   4   3   5
   4   2   5   1   3   6
   3   5   6   2   4   1
   3   2   6   1   4   5



## b) Fitness calculation

### Total travel distance for each possible sequence of cities

In [11]:
function individuals = distanceCalculation(pop,d)
    
    # This function returns a list with two elements.
    # The first 1 element contains the list that is received as input.
    # The second element contains a vector withthe total distance between cities

    
    daccs = zeros([size(pop)(1),size(pop)(2)+1]);

        for i = 1:(size(pop)(1))
            dacc = 0;

            for j = 1:(size(pop)(2)-1)
                dacc += d(pop(i,j),pop(i,j+1));
            end

            daccs(i,:) = [pop(i,:),dacc];
            
        end
    
    individuals{1} = pop;
    individuals{2} = daccs(:,size(daccs)(2));

end

In [12]:
generation0 = distanceCalculation(pop = generation0, d = d)

generation0 =
{
  [1,1] =

     2   4   6   5   1   3
     6   2   5   1   4   3
     6   3   2   4   5   1
     1   6   3   4   5   2
     2   6   5   4   1   3
     5   1   3   2   6   4
     5   2   6   3   1   4
     4   1   2   5   3   6
     1   2   4   5   6   3
     1   2   3   5   4   6
     6   5   2   3   1   4
     5   6   4   2   3   1
     3   2   5   6   1   4
     2   1   5   4   3   6
     5   6   1   2   4   3
     4   1   6   5   2   3
     1   6   2   4   3   5
     4   2   5   1   3   6
     3   5   6   2   4   1
     3   2   6   1   4   5

  [1,2] =

     457.15
     358.86
     368.19
     223.67
     382.17
     449.25
     320.03
     381.80
     364.84
     294.38
     350.05
     405.82
     354.88
     255.34
     414.39
     354.01
     274.62
     418.35
     360.47
     306.94

}



### Computation of the fitness of each individual (1/distance)

In [13]:
function individuals = fitness(individuals)
    
    # This function returns a list with three elements.
    # The first two elements corresponds are the same elements of the list received as an input.
    # The third element of the list includes a vector with the fitness of each individual. 

    individuals{3} = individuals{2};

    for i=1:size(individuals{1})(1)

        individuals{3}(i,1) = 1/individuals{2}(i);

    end 

end

In [14]:
generation0 = fitness(generation0)

generation0 =
{
  [1,1] =

     2   4   6   5   1   3
     6   2   5   1   4   3
     6   3   2   4   5   1
     1   6   3   4   5   2
     2   6   5   4   1   3
     5   1   3   2   6   4
     5   2   6   3   1   4
     4   1   2   5   3   6
     1   2   4   5   6   3
     1   2   3   5   4   6
     6   5   2   3   1   4
     5   6   4   2   3   1
     3   2   5   6   1   4
     2   1   5   4   3   6
     5   6   1   2   4   3
     4   1   6   5   2   3
     1   6   2   4   3   5
     4   2   5   1   3   6
     3   5   6   2   4   1
     3   2   6   1   4   5

  [1,2] =

     457.15
     358.86
     368.19
     223.67
     382.17
     449.25
     320.03
     381.80
     364.84
     294.38
     350.05
     405.82
     354.88
     255.34
     414.39
     354.01
     274.62
     418.35
     360.47
     306.94

  [1,3] =

     0.0021875
     0.0027866
     0.0027160
     0.0044709
     0.0026166
     0.0022259
     0.0031247
     0.0026192
     0.0027409
     0.0033970
     0.0028567
    

## c) Choice of parents to create the next generation of individuals

In [15]:
function [individuals,parents] = chooseParents(individuals)
    
    # This function returns a list with four elements.
    # The first three elements corresponds are the same elements of the list received as an input.
    #The fourth element contains a vector with 0's and 1's. Individuals selected as parents receives the value 1.

    individuals{4} = individuals{3};

    individualsCopy = individuals;

    #probParent = individuals{3}/sum(individuals{3})

    #First best-fitted individual

    [maxVal1,maxIndex1] = max(individuals{3});

    #Second best-fitted individual
    individualsCopy{3}(maxIndex1) = -1*individualsCopy{3}(maxIndex1);
    [maxVal2,maxIndex2] = max(individualsCopy{3});

    #Create a column with binary variables that takes the value 1 if the individual is parent or zero, otherwise. 
    individuals{4}=zeros(size(individuals{1})(1),1);

    individuals{4}(maxIndex1) = 1;
    individuals{4}(maxIndex2) = 1;

end

In [16]:
chooseParents(generation0)

ans =
{
  [1,1] =

     2   4   6   5   1   3
     6   2   5   1   4   3
     6   3   2   4   5   1
     1   6   3   4   5   2
     2   6   5   4   1   3
     5   1   3   2   6   4
     5   2   6   3   1   4
     4   1   2   5   3   6
     1   2   4   5   6   3
     1   2   3   5   4   6
     6   5   2   3   1   4
     5   6   4   2   3   1
     3   2   5   6   1   4
     2   1   5   4   3   6
     5   6   1   2   4   3
     4   1   6   5   2   3
     1   6   2   4   3   5
     4   2   5   1   3   6
     3   5   6   2   4   1
     3   2   6   1   4   5

  [1,2] =

     457.15
     358.86
     368.19
     223.67
     382.17
     449.25
     320.03
     381.80
     364.84
     294.38
     350.05
     405.82
     354.88
     255.34
     414.39
     354.01
     274.62
     418.35
     360.47
     306.94

  [1,3] =

     0.0021875
     0.0027866
     0.0027160
     0.0044709
     0.0026166
     0.0022259
     0.0031247
     0.0026192
     0.0027409
     0.0033970
     0.0028567
     0.00246

In [17]:
function parents = createParents(individuals)

# This function returns a list with three elements that refer to the individuals selected as parents.
# (element 1: sequence of cities, element 2: total distance, element 3: fitness)

individuals = chooseParents(individuals);

parents = {:};

count = 1;

for i = 1:size(individuals{4})(1)

    if individuals{4}(i) == 1

    parents{1}(count,:) = individuals{1}(i,:);
    parents{2}(count,:) = individuals{2}(i,:);
    parents{3}(count,:) = individuals{3}(i,:);
    
    count++;

    end

end


end

In [18]:
parentsG0 = createParents(generation0)

parentsG0 =
{
  [1,1] =

     1   6   3   4   5   2
     2   1   5   4   3   6

  [1,2] =

     223.67
     255.34

  [1,3] =

     0.0044709
     0.0039163

}



## d) Crossover

### Check if a gene (city) exist in a chromosome (sequence of cities)

In [19]:
function geneExist = containGene(child,gene)
    
    # This function is used by the function crossover()
    
    geneExist = false;

    for i=1:length(child)

        if child(i) == gene

            geneExist = true;

        end

    end

end

### Crossover between the two parents

In [20]:
function child = crossover(parents)
    
    #This function received a list with the parents' characteristics and performs the crossover operation to return a child

    nParents = size(parents{1})(1);
    chromosomeSize = size(parents{1})(2);

    %Select a random crossover point
    indexCO = randi([2,chromosomeSize],1,1);

    %Select the parent (parentChromosome1) that is used to start the crossover
    parentCO = randi(nParents,1,1);
    chromosomeParent1 = parents{1}(parentCO,:);
    chromosomeParent2 = parents{1}(1,:);

    if parentCO == 1
        chromosomeParent2 = parents{1}(2,:);
    end

    child = chromosomeParent1;

    #Genes from parent 1
    for i=1:length(child)

        if i < indexCO
            child(i) = 0;
        end

    end

    #Genes from parent 2
    genePosition = 1;
    for i=1:(indexCO-1)

        implant = false;

        while implant == false 
            geneExist = containGene(child,chromosomeParent2(genePosition));

            if geneExist == true
                genePosition++;
                implant = false;

            else
                child(i) = chromosomeParent2(genePosition);
                implant = true;
                genePosition++;
            end

        end

    end
    
end

In [21]:
childG0 = crossover(parentsG0)

childG0 =

   1   6   3   4   5   2



## e) Mutation

In [22]:
function child = mutation(child, pm)
    
    #This function received a child and then performs the mutation operation on that child
    
    childCopy = child;
    chromosomeSize = length(child);

    %Select two random mutation points
    indexM1 = randi([1,chromosomeSize],1,1);
    indexM2 = randi([1,chromosomeSize],1,1);
    
    %Mutation is done with a 'pm'% chance
    mutationProbThreshold = rand(1);
    
    if mutationProbThreshold < pm
    
        childCopy(indexM1) = child(indexM2);
        childCopy(indexM2) = child(indexM1);
        
    end
    
    child = childCopy;

end

In [23]:
childG0 #With no mutation
childG0 = mutation(childG0, pm = 0.5) # Child with mutation (setting a 50% probability of mutation)

childG0 =

   1   6   3   4   5   2

childG0 =

   1   6   3   4   5   2



## f) Next Generation

### Size of the next generations 

In [24]:
sizeNextGenerations = 1*size(generation0{1})(1) #Define the same size of the initial generation (generation 0)

sizeNextGenerations =  20


### f) Check if the child exists in a generation

In [25]:
function childExist = containChild(child,children)
    
    # This function prevents to have two identical childs in a generation 
    
    childExist = false;
    
    for i=1:size(children)(1)
    
        counterEqualGenes = 0;
        
        for j= 1:length(children(i,:))
        
            if children(i,:)(j) == child(j)
                counterEqualGenes++;
            end
     
        end
        
        if counterEqualGenes == length(child)
            childExist = true;
        end


    end

end

# 2) Genetic algorithm 

In [26]:
function generations = GA(initialGeneration, nGenerations,sizeNextGenerations,d,pm)
    
    #This function uses almost all the previous functions and it requires the following inputs:
    
    # initialGeneration: Matrix with the sequence of cities associated to the individuals of the initial generation (generation 0)
    # nGenerations: Number of the generations. if nGenerations is equal to 1, this function returns a list describing generation 0
    # sizeGeneration: number of individuals in each of the next generations
    # d: matrix of distance between cities
    # pm: probability of mutation
    
    #It returns a list ("generations"). The first element contains a list the characteristics of the individuals of generation 0
    # The next elements of the list contains a list with the characteristics of one of the next generations. 
    # The elements of the list of each generation contains the following:
    
    #1: Matrix of individuals of the generation 
    #2: Vector with total distance of each individual
    #3: Vector with fitness of each individual (1/d)
    #4: Vector with the sequence of cities associated to the best individual of the generation
    #5: Scalar with total distance of the best individual
    #6: Computation time of the functions executed to generate the list of each generation (in seconds)
    
    generations = {:};
    
    currentGeneration{1} = initialGeneration;
    
    #This process is iteratively repeated for each generation
    
    for i=0:(nGenerations)      
        
        t=cputime;
                
        if i == 0
            
            #Information about the initial generation
            currentGeneration  = distanceCalculation(currentGeneration{1},d);
            currentGeneration = fitness(currentGeneration);
            [maxVal,maxIndex] = max(currentGeneration{3});
            currentGeneration(4) = currentGeneration{1}(maxIndex,:); #Best individual
            currentGeneration(5) = currentGeneration{2}(maxIndex); #Total distance of Best individual
            currentGeneration(6) = cputime-t;
            
        end
               
        if i > 0        

            parents = createParents(previousGeneration);
            
            #Include parents in the next generation
            currentGeneration{1}(1,:) = parents{1}(1,:);
            currentGeneration{1}(2,:) = parents{1}(2,:);
            
            #Create child from parents
            child = crossover(parents);
            child = mutation(child,pm);
            
            #Include first child in the next generation
            currentGeneration{1}(3,:) = child;

            #This loop is repeated until reaching the number of individuals in a generation
            
            for j=4:sizeNextGenerations

                 newChild = mutation(crossover(parents),pm);

                 #Verify whether a new child is different to the existing children in the generation
                 while(containChild(child = newChild, children = currentGeneration{1}) == true)

                     newChild = mutation(crossover(parents),pm);

                 end

                 currentGeneration{1}(j,:) = newChild;
                 
                #Information about the new generation
                currentGeneration  = distanceCalculation(currentGeneration{1},d);
                currentGeneration = fitness(currentGeneration);
                [maxVal,maxIndex] = max(currentGeneration{3});
                currentGeneration(4) = currentGeneration{1}(maxIndex,:); #Best individual
                currentGeneration(5) = currentGeneration{2}(maxIndex); #Total distance of Best individual
                currentGeneration(6) = cputime-t;

            end
        
        end
        
        generations{i+1} = currentGeneration;
            
        previousGeneration = currentGeneration;
            
        currentGeneration = {};
        
    end

end

# 3) Application of the genetic algorithm using different numbers of generations

## a) Generation 0

In [27]:
generation0 = createGeneration(totalPop = totalPop,sizeGen = sizeGeneration0);

## b) Genetic algorithm using one generation (first element of the list is generation 0, second element is generation 1)

In [28]:
generations01 = GA(initialGeneration = generation0, nGenerations = 1, sizeNextGenerations = 10, d = d, pm = 0.4)

generations01 =
{
  [1,1] =
  {
    [1,1] =

       4   5   6   2   1   3
       5   2   1   4   6   3
       1   4   3   5   2   6
       3   2   4   6   1   5
       6   3   5   1   2   4
       5   6   2   1   3   4
       2   3   1   6   5   4
       3   1   5   4   6   2
       4   1   2   6   3   5
       5   6   3   4   1   2
       2   6   5   1   4   3
       3   5   1   6   2   4
       1   4   6   2   3   5
       4   2   3   1   6   5
       5   4   6   1   3   2
       4   1   6   2   3   5
       6   4   3   1   5   2
       6   3   4   1   2   5
       3   1   6   5   4   2
       2   1   6   5   4   3

    [1,2] =

       382.42
       306.60
       270.98
       344.45
       331.92
       379.99
       293.25
       284.92
       348.50
       378.20
       372.58
       277.47
       281.37
       347.23
       358.71
       283.75
       332.84
       380.30
       274.05
       278.41

    [1,3] =

       0.0026149
       0.0032616
       0.0036903
       0.0029032

## c) Genetic algorithm using two generations

In [29]:
generations012 = GA(initialGeneration = generation0, nGenerations = 2, sizeNextGenerations = 10, d = d, pm = 0.2)

generations012 =
{
  [1,1] =
  {
    [1,1] =

       4   5   6   2   1   3
       5   2   1   4   6   3
       1   4   3   5   2   6
       3   2   4   6   1   5
       6   3   5   1   2   4
       5   6   2   1   3   4
       2   3   1   6   5   4
       3   1   5   4   6   2
       4   1   2   6   3   5
       5   6   3   4   1   2
       2   6   5   1   4   3
       3   5   1   6   2   4
       1   4   6   2   3   5
       4   2   3   1   6   5
       5   4   6   1   3   2
       4   1   6   2   3   5
       6   4   3   1   5   2
       6   3   4   1   2   5
       3   1   6   5   4   2
       2   1   6   5   4   3

    [1,2] =

       382.42
       306.60
       270.98
       344.45
       331.92
       379.99
       293.25
       284.92
       348.50
       378.20
       372.58
       277.47
       281.37
       347.23
       358.71
       283.75
       332.84
       380.30
       274.05
       278.41

    [1,3] =

       0.0026149
       0.0032616
       0.0036903
       0.002903