# 1) Construya una red de 5 ciudades y una matriz de distancias de viajes usando números aleatorios entre 1 y 100. Imprima la matriz de distancias de viaje entre ciudades.

## Number of cities to be visited

In [1]:
n = 5

n =  5


## Matrix of distances between cities with random numbers

In [2]:
function d = distanceMatrixCities(n)

    d = 100*rand(n);

    ## Fill diagonal with zeros
    i = 1;
    while(i<=n)
        d(i,i) = 0;
        i++;
    end

end

In [3]:
d = distanceMatrixCities(n)

d =

    0.00000   63.80209    8.12256   98.33981   13.38512
   57.15393    0.00000   91.76719    8.55611   50.00122
   52.68217   80.19547    0.00000   22.43222   20.61195
    4.46175   42.70986   32.65692    0.00000   80.08154
   55.48513   88.52970   57.12394   97.39850    0.00000



# 2) Genere una lista con todas las posibles formas de viajar entre todas las ciudades. Impriman en consola la secuencia de ciudades y la distancia total recorrida en cada caso. Por u ́ltimo, imprima la distancia m ́ınima.

## Possible sequences of visited cities (e.g. 1,2,3,4,5 and 1,3,2,4,5)

In [4]:
p = perms([1:n]);

In [5]:
size(p)

ans =

   120     5



## Total travelled distance in each sequence of cities

In [6]:
function daccs = distanceCalculation(cities,d)

    daccs = zeros([size(cities)(1),size(cities)(2)+1]);

    for i = 1:(size(cities)(1))
        dacc = 0;
        
        for j = 1:(size(cities)(2)-1)
            dacc += d(cities(i,j),cities(i,j+1));
        end
        
        daccs(i,:) = [cities(i,:),dacc];
    
    end
end

In [7]:
daccs = distanceCalculation(cities = p, d = d)

daccs =

     5.0000     4.0000     3.0000     2.0000     1.0000   267.4048
     5.0000     4.0000     3.0000     1.0000     2.0000   246.5397
     5.0000     4.0000     2.0000     3.0000     1.0000   284.5577
     5.0000     4.0000     2.0000     1.0000     3.0000   205.3849
     5.0000     4.0000     1.0000     3.0000     2.0000   190.1783
     5.0000     4.0000     1.0000     2.0000     3.0000   257.4295
     5.0000     3.0000     4.0000     2.0000     1.0000   179.4199
     5.0000     3.0000     4.0000     1.0000     2.0000   147.8200
     5.0000     3.0000     2.0000     4.0000     1.0000   150.3373
     5.0000     3.0000     2.0000     1.0000     4.0000   292.8131
     5.0000     3.0000     1.0000     4.0000     2.0000   250.8558
     5.0000     3.0000     1.0000     2.0000     4.0000   182.1643
     5.0000     2.0000     4.0000     3.0000     1.0000   182.4249
     5.0000     2.0000     4.0000     1.0000     3.0000   109.6701
     5.0000     2.0000     3.0000     4.0000     1.00

## Sequence of cities with the minimum total distance (optimal solution)

### Function that returns the index of the sequence of cities with the minimim total distance

In [8]:
function minS = minimumTotalDistance(daccs,nCities)

    minD = min(daccs(:,nCities+1));
    minS = 1;

    for i = 1:size(daccs)(1)
        if(daccs(i,size(daccs)(2))==minD)
            minS = i;
        end
    end

end

In [9]:
minS = minimumTotalDistance(daccs,nCities = n)

minS =  84


In [10]:
fprintf('Sequence of cities: %s\n',sprintf('%d ', daccs(minS,1:size(daccs)(2)-1)))
fprintf('Minimum distance: %s\n',sprintf('%d ', daccs(minS,size(daccs)(2))))

Sequence of cities: 2 4 1 3 5 
Minimum distance: 41.7524 


# 3) Repita el ejercicio para 100 ciudades. ¿Cuánto tarda su algoritmo en encontrar la distancia mínima?

## Function that solve the TSP for any number of cities

In [11]:
function [n,minSeq,minDist,cpuTime] = TSP(nCities)

    n = nCities;
    d = distanceMatrixCities(n);
    t=cputime;

    p = perms([1:n]);

    daccs = distanceCalculation(cities = p, d = d);

    minS = minimumTotalDistance(daccs,nCities = nCities)

    minSeq = daccs(minS,1:(size(daccs)(2)-1));
    minDist = daccs(minS,size(daccs)(2));
    cpuTime = cputime-t;


end

## Function to print results

In [12]:
function printResults(n,minSeq,minDist,cpuTime)

    fprintf('Number of cities: %s\n',sprintf('%d ',n))
    fprintf('Sequence of cities: %s\n',sprintf('%d ',minSeq))
    fprintf('Minimum distance: %s\n',sprintf('%d ', minDist))
    printf('Total cpu time: %f seconds\n', cpuTime)

end

## Executing our algorithm to solve the TSP for 4,5,6,7 and 8 cities

### 4 Cities

In [13]:
[a1,a2,a3,a4] = TSP(nCities = 4); printResults(a1,a2,a3,a4)

minS =  13
Number of cities: 4 
Sequence of cities: 2 4 3 1 
Minimum distance: 118.424 
Total cpu time: 0.010581 seconds


### 5 Cities

In [14]:
[a1,a2,a3,a4] = TSP(nCities = 5); printResults(a1,a2,a3,a4)

minS =  46
Number of cities: 5 
Sequence of cities: 4 1 3 2 5 
Minimum distance: 87.4006 
Total cpu time: 0.042840 seconds


### 6 Cities

In [15]:
[a1,a2,a3,a4] = TSP(nCities = 6); printResults(a1,a2,a3,a4)

minS =  507
Number of cities: 6 
Sequence of cities: 2 5 6 3 4 1 
Minimum distance: 38.031 
Total cpu time: 0.236152 seconds


### 7 Cities

In [16]:
[a1,a2,a3,a4] = TSP(nCities = 7); printResults(a1,a2,a3,a4)

minS =  605
Number of cities: 7 
Sequence of cities: 7 1 6 5 2 4 3 
Minimum distance: 97.7847 
Total cpu time: 1.552743 seconds


### 8 Cities

In [17]:
[a1,a2,a3,a4] = TSP(nCities = 8); printResults(a1,a2,a3,a4)

minS =  2396
Number of cities: 8 
Sequence of cities: 8 4 6 1 2 7 3 5 
Minimum distance: 122.825 
Total cpu time: 11.158843 seconds


#### From the previous results, we expect that for 100 cities the algorithm will take a huge amount of time. The computational time by using a brute force approach to solve the travelling salesman problem growth at non-polynomial time.Indeed, if you execute this function for 100 cities, Octave will crash or your computer will shutdown.

# 4. Programe el algoritmo de Dijkstra para encontrar la distancia mínima entre una ciudad y el resto de las ciudades

### Distances matrix

* We first create a matrix with the distance between nodes. If there is no arcs between two nodes, the distance will be equal to infinity . The distance between a node and itself is 0. 

In [18]:
d = [
0   5   1   inf 1   inf  inf; #Node 1
inf 0   inf inf 2   inf  inf; #Node 2
inf inf 0   inf 4   2    inf; #Node 3
inf 1   inf 0   inf inf  5  ; #Node 4
inf inf inf 2   0   1    9  ; #Node 5
inf inf inf inf inf 0    7  ; #Node 6
inf inf inf inf inf inf  0  ; #Node 7
] 

d =

     0     5     1   Inf     1   Inf   Inf
   Inf     0   Inf   Inf     2   Inf   Inf
   Inf   Inf     0   Inf     4     2   Inf
   Inf     1   Inf     0   Inf   Inf     5
   Inf   Inf   Inf     2     0     1     9
   Inf   Inf   Inf   Inf   Inf     0     7
   Inf   Inf   Inf   Inf   Inf   Inf     0



## Visited and non-visited nodes

* A vector stores the information on visited nodes.
* The vector of visited nodes contains no values initially
* The vector of non-visited nodes contains all nodes initially

In [19]:
visitedNodes = zeros(0,1)
nonVisitedNodes = (1:size(d)(1))

visitedNodes = [](0x1)
nonVisitedNodes =

   1   2   3   4   5   6   7



### Predecessor nodes

* The predecesor of each node is stored in a vector with length equal to the number of nodes of the network. 
* The initial values in this vector are -1 and it is updated when a node is added to the list of visited nodes

In [20]:
predecessors =  -1*ones(1,size(d)(1))

predecessors =

  -1  -1  -1  -1  -1  -1  -1



## Current minimum distances

* A vector stores the current value of the minimum distance to each node
* The initial values in this vector are infinity and the elements are updated along the iterations of the algorithm

In [21]:
minDistances = inf*ones(1,size(d)(1))

minDistances =

   Inf   Inf   Inf   Inf   Inf   Inf   Inf



## Dijkstra Algorithm 

In [22]:
function [nodes, predecessors, minDistances] = dijkstra(d,nodeI,nodeM)
    
    nNodes = size(d)(1);
    nodes = (1:nNodes);
    
    visitedNodes = zeros(0,1); #Empty row vector with zeros
    nonVisitedNodes = (1:nNodes); #Row vector with nonVisitedNodes
    predecessors =  -1*ones(1,nNodes);
    minDistances = inf*ones(1,nNodes);
    nIteration = 0;
    minNodeIteration = 0;
 
 
    while (minNodeIteration != nodeM) #The algorithm finishes when the destination node is added to the list of visited nodes
        
        #Iteration 0 
        if nIteration == 0
            visitedNodes(1) = nodeI;
            nonVisitedNodes = nonVisitedNodes(nonVisitedNodes~=nodeI); #Remove the origin node from the list nonVisitedNodes 
            predecessors(nodeI) = -1;
            minDistances(nodeI) = d(nodeI,nodeI); #Equal to 0
            nIteration = nIteration + 1;
            
        else #Next iterations
            
            minNodeIteration = 0;
            minDistIteration = inf;
            
            for i = 1:(size(visitedNodes)(2))
            
                for j = 1:size(nonVisitedNodes)(2)
                    
                    
                    if (minDistances(visitedNodes(i))+d(visitedNodes(i),nonVisitedNodes(j)))<=minDistances(nonVisitedNodes(j))
                        
                        if minDistances(visitedNodes(i))+d(visitedNodes(i),nonVisitedNodes(j)) != inf 
                            minDistances(nonVisitedNodes(j)) = minDistances(visitedNodes(i))+d(visitedNodes(i),nonVisitedNodes(j));
                            predecessors(nonVisitedNodes(j)) = visitedNodes(i);
                        end
                        
                        if minDistances(nonVisitedNodes(j))<=minDistIteration #Store information on the node with minimum distance
                            
                            minDistIteration = minDistances(nonVisitedNodes(j));
                            minNodeIteration = nonVisitedNodes(j);
                        end                        
                    end
            
                end
                
            end
            
            if minNodeIteration != 0 #When the node is accesible f
                
                visitedNodes(size(visitedNodes)(2)+1) = minNodeIteration; #Add node with minimum distance to the list of the visited nodes
                nonVisitedNodes = nonVisitedNodes(nonVisitedNodes~=minNodeIteration); #Remove the visited node from the list nonVisitedNodes
            end
            
            nIteration = nIteration + 1; #next iteration
            
        end
        
    end

end

## To test the algorithm, we will use the same network provided in problem 2, homework 11

* Distance from node 1 to node 7

In [23]:
[nodes, predecessors, minDistances] = dijkstra(d=d,nodeI = 1, nodeM = 7)

nodes =

   1   2   3   4   5   6   7

predecessors =

  -1   4   1   5   1   5   4

minDistances =

   0   4   1   3   1   2   8



* Distance from node 3 to node 7

In [24]:
[nodes, predecessors, minDistances] = dijkstra(d=d,nodeI = 4, nodeM = 7)

nodes =

   1   2   3   4   5   6   7

predecessors =

  -1   4  -1  -1   2   5   4

minDistances =

   Inf     1   Inf     0     3     4     5



Note that node 1 and 3 are not accessible from node 4 so their distances are infinity and their predecessors are -1